DROP TABLE IF EXISTS QUESTION CASCADE;
DROP TABLE IF EXISTS ANSWER CASCADE;
DROP TABLE IF EXISTS CHANNEL;
CREATE TABLE QUESTION (
    ID          BIGINT AUTO_INCREMENT  NOT NULL,
    VERSION     BIGINT       NOT NULL,
    CHANNEL_ID  BIGINT,
    STATUS      VARCHAR(100)  NOT NULL,
    TITLE       VARCHAR(200)  NOT NULL,
    CONTENT        VARCHAR(200)  NOT NULL,
    CREATED_BY  VARCHAR(100),
    CREATED_AT  TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ANSWER (
    ID          BIGINT AUTO_INCREMENT  NOT NULL,
    VERSION     BIGINT       NOT NULL,
    QUESTION_ID BIGINT       NOT NULL,
    CONTENT        VARCHAR(200)  NOT NULL,
    CREATED_BY  VARCHAR(100),
    CREATED_AT  TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (ID)
--     FOREIGN KEY (QUESTION_ID) references QUESTION
);
-- ALTER TABLE FK_ANSWER_QUESTION ADD FOREIGN KEY(QUESTION_ID) references QUESTION(ID)
ALTER TABLE ANSWER ADD FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID);


CREATE TABLE CHANNEL (
    ID                 BIGINT AUTO_INCREMENT  NOT NULL,
    NAME               VARCHAR(100)  NOT NULL,
    DESCRIPTION        VARCHAR(255)  NOT NULL,
    CREATED_BY         VARCHAR(100),
    CREATED_AT         TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (ID)
);
